### ISSUE TITLE
Cannot find binding of given name: 339

### ISSUE THREAD

**Issue by SLAVIK555** [yinguobing/yolov5-trt#2]
Good time of day!
I have successfully compiled the code from this repository, but when I tried to run it, I got the following error:

> 3: Cannot find binding of given name: 339
ERROR: failed to get output by name: 339

Please tell me how I can solve this problem
And could you tell me where you got these values from ' "339", "392", "445", "output" '? [Link to code](https://github.com/yinguobing/yolov5-trt/blob/b4a9e47d583af9317e3c95d68a3b5d7a02077132/yolov5.cpp#L92)

--------------------------------------------------------------

I use Jetson Nano with JetPack 4.6.1, CUDA 10.2 and TensorRT 8.2.1.8

--------------------------------------------------------------

Steps to reproduce my error:

Step 1:
Download pretrained yolov5s model from link from your tutorial [Link to model](https://github.com/ultralytics/yolov5/releases/download/v6.1/yolov5s.pt)

Step 2:
Convert model to ONNX using the following command
`python3 export.py --weights=yolov5s.pt --include=onnx`

Step 3:
Convert ONNX model to TensorRT using the following command
`/usr/src/tensorrt/bin/trtexec --onnx=yolov5s.onnx --saveEngine=yolov5s.engine`

I would be grateful for any advice

**Comment by Xbotgo-Justin1** [comment]
i also meet the same question
 justin@DESKTOP-NIK28BI:~/yolov5-trt/build$ ./yolov5 yolov5s.engine bus.jpg
TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.5.0
TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.5.0
CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
3: Cannot find binding of given name: 339
ERROR: failed to get output by name: 339

**Comment by yinguobing** [comment]
`339` is the name of the output node. If this output node is not available, please check the ONNX model for the correct output node names.

Note Yolov5s was used in this repo.

![Screenshot from 2022-12-11 13-42-34](https://user-images.githubusercontent.com/10267910/206888424-09482fec-8d9a-48a9-a1c6-0fa17f3af339.png)

**Comment by SLAVIK555** [comment]
@yinguobing , Thank you for your answer. But when i try to convert my .pt model to .onnx model using the command `python3 export.py --weights=yolov5s.pt --include=onnx`, i get a model like this:

![Screenshot from 2022-12-11 09-28-33](https://user-images.githubusercontent.com/47494485/206896384-623e75ec-a904-4970-bfc3-3593a84e217a.png)

So, could you tell me, which command should i use for converting my model with the same outputs as you model?

**Comment by Xbotgo-Justin1** [comment]
![image](https://user-images.githubusercontent.com/43391856/206908812-8279dfe8-da0a-4aa6-8ec7-f95388025582.png)
@yinguobing @SLAVIK555   both SlAVIK555 and me run into same trouble,surely!

**Comment by Xbotgo-Justin1** [comment]
and yolov5s is used truely!

**Comment by yinguobing** [comment]
It might be the model file rather than the command that caused this. Could you please try this one: 
https://github.com/ultralytics/yolov5/releases/download/v6.1/yolov5s.pt

**Comment by SLAVIK555** [comment]
@yinguobing , Thank you for your model. But when i try to convert it, i get same result as in my previous [post](https://github.com/yinguobing/yolov5-trt/issues/2#issuecomment-1345506627). 

Could you tell me, what checkout of YOLOv5 repo you use? When i worked with yolov5 and onnx 10 mounths ago, i hadn't such problems, like now

**Comment by yinguobing** [comment]
The commit ID is `b0ba101a` when exporting the model.

I noticed your model output node `output` has exactly the same shape of `1 x 25200 x 85`. Maybe you can omit the other output nodes in the code. `339, `392`, `445` are not required for post processing.

**Comment by SLAVIK555** [comment]
@yinguobing, Thank you. I will try to export model with older version of YOLOv5 repo

**Comment by Xbotgo-Justin1** [comment]
![image](https://user-images.githubusercontent.com/43391856/207576000-62bf626a-af04-4d45-960e-f7d3bda08c94.png)
make correct onnx output with yolov5 tag6.1 repo and yolov5 tag 6.1 weights!

**Comment by Xbotgo-Justin1** [comment]
> 
but still error!!!
(base) justin@DESKTOP-NIK28BI:~/yolov5-trt/build$ ./yolov5  yolov5s.engine bus.jpg
TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.5.0
TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.5.0
CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
3: Cannot find binding of given name: 339

**Comment by yinguobing** [comment]
It's close. Please replace the node names that can not be found with those in your new model.

**Comment by SLAVIK555** [comment]
@justinge , Thank for your answer, yolov5 tag6.1 repo and yolov5 tag 6.1 weights work correct for me. Sorry, I haven't been in touch for a long time, I think the issue can be closed

**Comment by yinguobing** [comment]
Glad to hear that 😄

**Comment by DeqingSun** [comment]
OK let me share some experience about the "Cannot find binding of given name: 339"

Here is image of the op's netron capture.

![206888424-09482fec-8d9a-48a9-a1c6-0fa17f3af339](https://github.com/yinguobing/yolov5-trt/assets/1385273/3bc42993-4d1e-40c8-8cff-30695ed4b942)

The output has 4 items, they are output, 339, 392, 445. The op is interested in the "output", which has 25200 entries and each entry has 85 numbers.

And here is netron capture of my model. 

![Screenshot 2024-02-02 150956](https://github.com/yinguobing/yolov5-trt/assets/1385273/bd6c0df4-7c92-470e-b7fb-357028ffc4cf)

It only has one output "OUTPUT0" and there are 25200 entries and each entry has 7 numbers.

To make this repo work for me, I need:

change https://github.com/yinguobing/yolov5-trt/blob/b4a9e47d583af9317e3c95d68a3b5d7a02077132/yolov5.cpp#L92 to "output0" only.

make https://github.com/yinguobing/yolov5-trt/blob/b4a9e47d583af9317e3c95d68a3b5d7a02077132/yolov5.cpp#L187 to [0] as that is the only array we have.

make https://github.com/yinguobing/yolov5-trt/blob/b4a9e47d583af9317e3c95d68a3b5d7a02077132/yolov5.cpp#L188 step to 7 because my entry only has 7 item. But the data format is the same so no need to change.

And it works!
